apiVersion: v3

name: gondwana
description: A modular-generic collection of templates to deploy any application

type: library
version: 0.1.0

kubeVersion: ">=1.24.0"

keywords:
  - modular
  - universal
  - production-ready

sources:
  - https://github.com/Yonatan-Shabot/Gondwana.git

maintainers:
  - name: Yonatan Shabot
    email: shabotyonatan@gmail.com
