apiVersion: v2

name: gondwana
description: A modular-generic collection of templates to deploy any application, used with mespotamia, which includes an implementation of the Gondwana framework.

type: library
version: 0.1.6

kubeVersion: ">=1.24.0"

sources:
  - https://github.com/Yonatan-Shabot/Gondwana.git

maintainers:
  - name: Yonatan Shabot
    email: shabotyonatan@gmail.com
