{{- define "gondwana.generic.ingress" }}
{{- range $values := .Values.services.generic }}
{{- range $port := $values.ports }}
{{- if $port.ingress }}
{{- include "gondwana.skeleton.ingress" (dict "parentName" $values.name "exposedPort" $port "root" $) }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}