{{- define "gondwana.skeleton.cronJob" }}
{{- /* This skeleton expects the following arguments inside the dict */}}
{{ $root := .root }} {{- /* Should be $
.context - The context for the cron job
.ports - A list of ports to be exoposed
.files - A list of files to be mounted in the pod
.envs - A list of envs that should be inserted into each pod
.volumes - A lsit of volumes to be mounted in each pod
*/}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .context.name }}
  labels:
    microservice/name: {{ .context.name | quote }}
    {{- include "gondwana.labels" $root | indent 4 }}
spec:
  schedule: {{ .context.cron | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: {{ .context.name }}
        spec:
          {{- include "gondwana.skeleton.pod" . | indent 10 }}
---
{{- end }}