{{- define "universal.skeleton.deployment" }}
{{- /* This skeleton expects the following arguments inside the dict */}}
{{ $root := .root }} {{- /* Should be $
.content - A list of files to be inserted
.files - This is a list of globalFiles that should be inserted into the deployment
*/}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .context.name }}
  labels:
    microservice/name: {{ .context.name | quote }}
    {{- include "universal.labels" $root | indent 4 }}
spec:
  replicas: {{ .context.replicaCount | default 1}}
  selector:
    matchLabels:
      app: {{ .context.name }}
  template:
    metadata:
      labels:
        app: {{ .context.name }}
    spec:
      {{- include "universal.skeleton.pod" . | indent 6 }}
---
{{- end }}