{{- define "universal.skeleton.ingress" }}
{{- /* This skeleton expects the following arguments inside the dict */}}
{{ $root := .root }} {{- /* Should be $
.parentName - the name of the service this manifest is a part of
.exposedPort - A list of files to be inserted
*/}}
apiVersion: r/v1
kind: networkPolicy
metadata:
  name: {{ .parentName }}-{{ .exposedPort.name }}
  labels:
    microservice/name: {{ .parentName | quote }}
    {{- include "universal.labels" $root | indent 4 }}
spec:
  rules:
    - host: {{ index (splitList "/" .exposedPort.ingress.url ) 0 }} 
      http:
        paths:
        - path: {{ regexReplaceAll "^.*?/" (.exposedPort.ingress.url ) "/" }} 
          pathType: Prefix
          backend:
            service:
              name: {{ .parentName }}
              port:
                number: {{ .exposedPort.targetPort }}
---
{{- end }}