{{- define "gondwana.skeleton.job" }}
{{- /* This skeleton expects the following arguments inside the dict */}}
{{ $root := .root }} {{- /* Should be $
.context - the context of the service this manifest is a part of
.ports - A list of ports to be exoposed
.files - A list of files to be mounted in the pod
.envs - A list of envs that should be inserted into each pod
.volumes - A lsit of volumes to be mounted in each pod
*/}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .context.name }}{{- include "gondwana.nameSuffix" $root}}{{- include "gondwana.nameSuffix" $root}}
  labels:
    microservice/name: {{ .context.name | quote }}
    {{- include "gondwana.labels" $root | indent 4 }}
spec:
  template:
    metadata:
      labels:
        parent: {{ .context.name | quote }}
    spec:
      {{- include "gondwana.skeleton.pod" . | indent 6 }}
---
{{- end }}