{{- define "gondwana.skeleton.networkPolicy" }}
{{- /* This skeleton expects the following arguments inside the dict */}}
{{ $root := .root }} {{- /* Should be $
.parentName - the name of the service this manifest is a part of
.exposedPort - The port configuration this network policy is allowing
*/}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ .parentName }}-{{ .exposedPort.targetPort }}
  labels:
    microservice/name: {{ .parentName | quote }}
    {{- include "gondwana.labels" $root | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ .parentName }}
  ingress:
    - ports:
        - protocol: {{ .exposedPort.protocol | default "TCP" }}
          port: {{ .exposedPort.targetPort }}
  policyTypes:
    - Ingress
---
{{- end }}