{{- define "gondwana.skeleton.sa" }}
{{- /* This skeleton expects the following arguments inside the dict */}}
{{ $root := .root }} {{- /* Should be $
.serviceAccount - the name of the service this serviceAccount
*/}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .serviceAccount }}
  labels:
    {{- include "gondwana.labels" $root | indent 4 }}
{{- end }}