{{- define "universal.skeleton.sa" }}
{{- /* This skeleton expects the following arguments inside the dict */}}
{{ $root := .root }} {{- /* Should be $
.serviceAccount - the name of the service this serviceAccount
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .serviceAccount }}
  labels:
    {{- include "universal.labels" $root | indent 4 }}
{{- end }}