{{- define "gondwana.skeleton.secret" }}
{{- /* This skeleton expects the following arguments inside the dict */}}
{{ $root := .root }} {{- /* Should be $
.name - the name of the service this manifest is a part of
.content - A list of files to be inserted
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- include "gondwana.labels" $root | indent 4 }}
stringData:
{{ toYaml .content | indent 2}}
{{- end }}